### ISSUE TITLE
update: github actions to latest actions

### ISSUE THREAD

**Issue by metaist** [metaist/LTS#7]
- [x] attrbox
- [x] castfit
- [x] cosmofy
- [x] ds
- [x] ezq
- [x] pdfmerge

```yaml
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up caches
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ matrix.python-version }}
```
