### ISSUE TITLE
update: 2025 build tools

### ISSUE THREAD

**Issue by metaist** [metaist/LTS#8]
Use standard:

- [ ] `LICENSE.md` (#6)
- [ ] `pyproject.toml` (#2, #4)
- [ ] `.github/ci.yaml` (#1, #3, #7)

Projects:
- [x] attrbox
- [x] castfit
- [x] cosmofy
- [ ] ds
- [ ] ezq
- [x] pdfmerge

**Comment by metaist** [comment]
We should support 3.13 where we can.

**Comment by metaist** [comment]
It took me so long to move on this that many of the bits need to be updated. Here is the latest.

<details><summary>.github/workflows/ci.yaml</summary>

```yaml
name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          uv tool install ds-run

      - name: Format & Lint (ruff, cspell)
        run: ds lint

      - name: Type check (ty, pyright, mypy)
        run: ds types

      - name: Run tests (pytest, coverage)
        run: ds test

      - name: Build docs (pdoc)
        run: ds docs
```
</details>

<details><summary>.github/workflows/codeql-analysis.yml</summary>

```yaml
name: "CodeQL"

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["python"]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
```
</details>

<details><summary>.github/workflows/pypi.yaml</summary>

```yaml
name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          uv toll install ds-run

      - name: Build package
        run: ds build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
```
</details>
